/*
Script generated by Aqua Data Studio 19.0.2-5 on jun-10-2024 12:37:31 PM
Database: hospital_final_jimenez
Schema: <All Schemas>
Objects: TABLE
*/
CREATE TABLE citas  ( 
	cita_id       	SERIAL NOT NULL,
	cita_paciente 	INTEGER NOT NULL,
	cita_medico   	INTEGER NOT NULL,
	cita_fecha    	DATE NOT NULL,
	cita_hora     	INTERVAL HOUR to MINUTE NOT NULL,
	cita_referencia	VARCHAR(5) NOT NULL,
	cita_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(cita_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE clinicas  ( 
	clinica_id       	SERIAL NOT NULL,
	clinica_nombre   	VARCHAR(50) NOT NULL,
	clinica_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(clinica_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE detalles  ( 
	detalle_id       	SERIAL NOT NULL,
	detalle_cita     	INTEGER NOT NULL,
	detalle_paciente 	INTEGER NOT NULL,
	detalle_medico   	INTEGER NOT NULL,
	detalle_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(detalle_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE especialidades  ( 
	espec_id       	SERIAL NOT NULL,
	espec_nombre   	VARCHAR(50) NOT NULL,
	espec_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(espec_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE medicos  ( 
	medico_id       	SERIAL NOT NULL,
	medico_nombre   	VARCHAR(50) NOT NULL,
	medico_espec    	INTEGER NOT NULL,
	medico_clinica  	INTEGER NOT NULL,
	medico_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(medico_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE pacientes  ( 
	paciente_id       	SERIAL NOT NULL,
	paciente_nombre   	VARCHAR(50) NOT NULL,
	paciente_dpi      	BIGINT NOT NULL,
	paciente_telefono 	BIGINT NOT NULL,
	paciente_situacion	SMALLINT DEFAULT 1 NOT NULL,
	PRIMARY KEY(paciente_id)
	ENABLED
)
LOCK MODE ROW;